# Generated by Django 4.1.1 on 2022-09-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('description', models.TextField(default='', max_length=2000, verbose_name='Оисание товара')),
                ('photo', models.CharField(default='', max_length=100, verbose_name='Фото товара')),
                ('category', models.CharField(choices=[('other', 'Разное'), ('noutbook', 'Ноутбуки'), ('smartphone', 'Смартфоны'), ('tv', 'Телевизоры'), ('monitor', 'Мониторы')], default='other', max_length=20, verbose_name='Категория')),
                ('balance', models.IntegerField(default=0, verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Стоимость')),
            ],
        ),
    ]
